### ISSUE TITLE
about relabel dataset 

### ISSUE THREAD

**Issue by SeungyounShin** [naver-ai/relabel_imagenet#8]
A sample of relabel dataset has shape of [2,5,15,15]

Could you explain what each axis means?

I believe that [0, :] means prediction confidence and [1:,] means predicted class number.

**Comment by hellbell** [comment]
Hi, are you looking at `label_map`?

https://github.com/naver-ai/relabel_imagenet/blob/6cd84dffe4ce8005395970b2938b3196d0958351/utils/relabel_functions.py#L15-L27

For the first dim of `label_map`, 
`label_map[0]` is a tensor for the prediction scores, and `label_map[1]` is for the class indices as you saying. 
The second dim indicates the top-k index because we only store the top-k label maps for storage efficiency.

**Comment by SeungyounShin** [comment]
![image](https://user-images.githubusercontent.com/20262536/132693669-b7edc2d5-dc09-41fb-a4bd-0bd964ee0039.png)

This is a sample image from the Imagenet and Relabel dataset. The dominant pixel value of label map is 769,  and I would like to know the class name of the number. Is there any way of converting this?

**Comment by SanghyukChun** [comment]
@SeungyounShin 
You can use this JSON data.
https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a
`769` is `'rule, ruler'`
